# Generated by Django 4.1.2 on 2022-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='korpus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
