# Generated by Django 4.1.2 on 2022-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_address_flat_alter_address_korpus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Addres'},
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='korpus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
