# Generated by Django 4.1.2 on 2022-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_customer_address_customer_flat_customer_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='flat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='house',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
